In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
for cell in a.flatten() :
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
for x in np.nditer(a, order='C') :
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for x in np.nditer(a, order='F') :    # F for fortran
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [6]:
for x in np.nditer(a, order='F', flags=['external_loop']) :   
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [7]:
for x in np.nditer(a, op_flags=['readwrite']) : 
    x = x*x
    
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.arange(12).reshape(3,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
b = np.arange(3,15,4).reshape(3,1)

print(b)

[[ 3]
 [ 7]
 [11]]


In [10]:
for x,y in np.nditer([a,b]) : 
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [11]:
b = np.arange(4).reshape(1,4)

print(b)

[[0 1 2 3]]


In [12]:
for x,y in np.nditer([a,b]) : 
    print(x,y)

0 0
1 1
2 2
3 3
4 0
5 1
6 2
7 3
8 0
9 1
10 2
11 3
